### ISSUE TITLE
Unable to use the dependency present in the POM file

### ISSUE THREAD

**Issue by ashfaqnisar** [ashfaqnisar/Swachh-Bharat-Assignment#6]
I am using Xstream to convert the data object into an XML file. But, whenever I run the JAR. I am receiving this error.
`Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/XStream
        at com.rubicon.swachh.App.main(App.java:21)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.XStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
`

**Comment by ashfaqnisar** [comment]
The issue was being caused by the <PluginManagement> tag. This tag was stopping the other plugins from being executed. The issue was solved in the **45th commit.**
